name: Deploy Python Function App - Jackson-Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: 'Jackson-Backend'
  PYTHON_VERSION: '3.10'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: 🔐 Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_78CEF60B352F4D798CD748A8CF73B20C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B93E55247C934391BE2662E112B6A393 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_61DB72DFEF1446C299160B767E5B028C }}

      - name: 📦 Deploy with remote build
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'jackson'
          package: '.'
          scm-do-build-during-deployment: true
